### ISSUE TITLE
Alternate path

### ISSUE THREAD

**Issue by firefart** [dirkjanm/adidnsdump#1]
Hi,
we just tried your tool and looks like the ldap paths can differ on old installations.

It looks like these are the possible DNS paths:
```text
CN=MicrosoftDNS,DC=DomainDNSZones,DC=<child domain>
CN=MicrosoftDNS,DC=ForestDNSZones,DC=<child domain>
CN=MicrosoftDNS,CN=System,DC=<child domain>
```

In our case there are some default entries in `DomainDNSZones`, but the main DNS data is located under `System`.

I modified this line locally to make it work, but maybe it would be best to add an option for this new path, or even enumerate both paths?
```text
dnsroot = 'CN=MicrosoftDNS,CN=System,%s' % domainroot
```

**Comment by dirkjanm** [comment]
Thanks for reporting this, could you test with the latest version and let me know if that fixes it?

**Comment by firefart** [comment]
Thanks works now using the legacy switch!
