### ISSUE TITLE
can't export any record when my domain exists in cn=system,dc=lab,dc=com

### ISSUE THREAD

**Issue by wqreytuk** [dirkjanm/adidnsdump#12]
my domain's dns record is sotred in DC=alb.com,CN=MicrosoftDNS,CN=System,DC=lab,DC=com

but when I use adidnsdump to export dns record, I got 0 records.

**Comment by dirkjanm** [comment]
can you show the output of --print-zones and your command and output of the tool?

**Comment by wqreytuk** [comment]
> 您可以显示--print-zones的输出以及该工具的命令和输出吗？

I've figured it out, iwith --legacy option, it worked, the reason maybe I update the win2000 DC to newer one, so the old dns zone is save in this place

**Comment by dirkjanm** [comment]
good to hear, I will add some improvements to make it more clear that these zones require different dump options

**Comment by wqreytuk** [comment]
> good to hear, I will add some improvements to make it more clear that these zones require different dump options

you're my idol, you've done a very good job for the security community, can I have your email? or send it to my email:  wochinijiamile@qq.com, just for easier communication

**Comment by wqreytuk** [comment]
> good to hear, I will add some improvements to make it more clear that these zones require different dump options

and I'm looking forward to your speech at black hat con in a few days

**Comment by dirkjanm** [comment]
sorry I don't really use email much for communications, but you can DM me on Twitter @_dirkjan
