### ISSUE TITLE
Discussion: Would removing the password parameter be a good idea?

### ISSUE THREAD

**Issue by zbalkan** [dirkjanm/adidnsdump#16]
Hi,

Since there is not a discussion page, I wanted to ask about the password parameter. Since it is a well-known [CWE](https://cwe.mitre.org/data/definitions/214.html), the rationale is obvious. The password can be leaked by just using `ps` or `top` command, to SIEMs thanks to `auditd`, bash history, etc.  I believe it is better to remove the `--password, -p` for all.

It may not be an issue in the attacker perspective depending on their OPSEC, but it can be a problem with blue team members and accidents happen. During detection engineering, it is possible to leak credentials.

What do you think?

**Comment by dirkjanm** [comment]
The password parameter is already optional, if you don't specify it it should prompt for it. If you are in an environment where command lines are logged then I wouldn't use the -p, however most of the time people will run this from a non-monitored system so it's much handier to have the option to specify it in the command line.
